### ISSUE TITLE
RFC: Organise Attribute Information for Trainees

### ISSUE THREAD

**Issue by AdColvin** [DFE-Digital/register-trainee-teachers#4336]
In our[ trainee_attributes](https://github.com/DFE-Digital/register-trainee-teachers/blob/61a1d29fe7965b72b9555d4c8f8e532691461b8e/app/models/api/trainee_attributes/v01.rb#L13) class, we have a long list of attributes and metadata for them split across multiple constants, and repeated in several places throughout the file. 

What if we move this information out into a YAML file or something and organise it more like this:

``` yaml
first_names:
  {
    required: true,
    nested: false,
    internal: false,
    type: "string",
    options: {
      default: "..."
    },
  }
date_of_birth:
  { 
    required: true, 
    nested: false, 
    internal: false, 
    type: "date", 
    options: {} 
}
```

We could then still use the constants we have in the attributes class, but make them much more concise: 

```ruby
ATTRIBUTES_PATH = File.join(__dir__, 'trainee_attributes.yml')
ATTRIBUTES = YAML.load_file(ATTRIBUTES_PATH).deep_symbolize_keys
REQUIRED_ATTRIBUTES = ATTRIBUTES.select { |_, config| config[:required] }.keys
INTERNAL_ATTRIBUTES = ATTRIBUTES.select { |_, config| config[:internal] }.keys
NESTED_ATTRIBUTES = ATTRIBUTES.select { |_, config| config[:nested] }.keys
```

That would mean we can keep the attributes class more focused on the validation logic, assigning attributes and that sort of thing, rather than housing all this data. It also means we can add new attributes, and change the metadata just by updating the yaml file.

If we like the pattern, we could also apply it to the other attribute classes.
